### ISSUE TITLE
Resource Busy Or Locked Error

### ISSUE THREAD

**Issue by irv075** [vitest-dev/vscode#371]
### Describe the bug

The extension throws a `resource busy or locked` exception intermittently. It seems to be trying to access files in the root of the C drive - usually `c:\DumpStack.log.tmp` or `c:\hiberfil.sys` (if dumpstack logging has been disabled).

After the error has been thrown I have to disable then re-enable the extension to get it running again - it will then fail again after an amount of time ranging from a few seconds to 15 minutes.

OS: Windows 10
VS Code:1.88.1
Vitest Extension: 0.8.6

### Reproduction

No special reproduction required, the exception is thrown even when no tests are being ran, just having the extension enabled for a period of time.

### Output

```shell
[INFO 9:48:24 AM] [DEBUG] Debugging started
[INFO 9:48:31 AM] [DEBUG] Starting debugging on localhost:9229
[INFO 9:48:31 AM] Running 1 file(s): src/components/SyntaxHighlighter/SyntaxHighlighter.test.tsx
[Worker] Debugger listening on ws://127.0.0.1:9229/d5664dcd-6649-4dda-a559-eb523bb9543e
For help, see: https://nodejs.org/en/docs/inspector
[Worker] Debugger attached.
[INFO 9:48:31 AM] [DEBUG] Debugging started
[Worker] node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///C:/Repositories/testapp/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:46060:10)
    at NodeFsHandler._boundHandleError (file:///C:/Repositories/testapp/node_modules/vite/dist/node/chunks/dep-DkOS1hkm.js:44533:43)
    at ReaddirpStream.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'C:\\hiberfil.sys'
}
```

### Version

0.8.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by hi-ogawa** [comment]
Quick googling is suggesting that this might be because of some plugins not following Vite's convention:
- https://github.com/underfin/vite-plugin-vue2/issues/24
- https://github.com/windicss/vite-plugin-windicss/issues/269

Can you check if you have any plugins which might be doing something similar?
Also, can you check if you can reproduce with `vitest` cli without vscode extension?

**Comment by irv075** [comment]
Apologies for the delay in replying.

I am not using any additional plugins for vitest, and only the React plugin for vite. The issue does not seem to be reproduced when using vitest cli

**Comment by hi-ogawa** [comment]
> only the React plugin for vite

Interesting. Actually official react plugin is also doing `/@react-refresh`  https://github.com/vitejs/vite-plugin-react/blob/814ed8043d321f4b4679a9f4a781d1ed14f185e4/packages/plugin-react/src/fast-refresh.ts#L5, so that's might be the culprit.

> The issue does seem to be reproduced when using vitest cli

Thanks for confirming. For now, I'll move this issue to Vitest repo, but I this it's also possible that the same issue can happen on Vite cli too. If that's the case, we need to report that to either Vite or React plugin https://github.com/vitejs/vite-plugin-react
