### ISSUE TITLE
Maximum call stack size exceeded in symlinked folders

### ISSUE THREAD

**Issue by alex-kinokon** [vitest-dev/vscode#487]
### Describe the bug

Opening a project from a symlinked location will cause the extension to fail with `There was an error during Vitest startup. Check the output for more details.`

### Reproduction

```sh
mkdir a
cd a
mkdir -p b/c
ln -s ./b/c ./c
```

in `c` folder, set up with the following files:

```json
{
  "devDependencies": {
    "vite": "^2.0.0",
    "vitest": "^2.1.2"
  }
}
```

```ts
// vitest.config.ts
import { defineConfig } from "vitest/config";

export default defineConfig({});
```

```ts
// src/a.test.ts
import { describe, it, expect } from "vitest";

describe("a", () => {
  it("should work", () => {
    expect(true).toBe(true);
  });
});
```

Now open the folder with `code ./c` (not `./b/c`).

### Output

```shell
[INFO 06:14:30] [API] Running Vitest v2.1.1 (templates/vitest.config.ts) with Node.js@v22.9.0: /opt/homebrew/bin/node 
[INFO 06:14:30] [Worker] [33mThe CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.[39m
[INFO 06:14:31] [API] Vitest v2.1.1 (templates/vitest.config.ts) process 84029 created
[Error 06:14:31] [Error RangeError] Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Tr (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:8:1942)
    at se (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:8:3664)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3597)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3569)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3569)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3569)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3569)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3569)
    at zr.getOrCreateFolderTestItem (/Users/name/.vscode-oss/extensions/vitest.explorer-1.2.18/dist/extension.js:22:3569)
    ...
```

### Version

1.2.18

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sheremet-va** [comment]
Fixed in 6e4431bf6fa0c86b2a1958383c8e320c6fe81fa3
