### ISSUE TITLE
Process exited unexpectedly when source code has parsing error

### ISSUE THREAD

**Issue by kayahr** [vitest-dev/vscode#521]
### Describe the bug

The extension crashes when saving a test file with parsing errors and it does not recover after fixing the code. Not sure what exactly is the trigger here because it behaves differently in very simple test cases. But I have a minimal example with a Node and Browser test where the crash happens in the browser test but not in the Node Test.

### Reproduction

1. Checkout minimal test project: https://github.com/kayahr/vitest-bugs-4
2. Run `npm i`
3. Open project in VSCode.
4. Open the `sum.node.test.js` file.
5. Remove the last code line to create a parser error => Vitest extension does not crash, it ignores the test file until the error is fixed. So perfect behavior.
6. Open the `sum.browser.test.js` file.
7. Remove the last code line to create a parser error => Vitest extension crashes (see screenshot below) and does not recover. It must be manually reloaded by clicking the "Refresh Tests" button in the Testing panel.

![image](https://github.com/user-attachments/assets/05902bdd-b988-415d-8167-6b87c9d1276a)

### Output

```shell
[INFO 1:48:03 PM] [v1.6.4] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 1:48:03 PM] [API] Running Vitest v2.1.4 (vitest-bug-4/vitest.workspace.js) with Node.js@v22.11.0: /usr/bin/node 
[INFO 1:48:04 PM] [API] Vitest v2.1.4 (vitest-bug-4/vitest.workspace.js) child process 207108 created
[INFO 1:48:04 PM] [VSCODE] Watching vitest-bug-4 with pattern **/*
[INFO 1:48:04 PM] [API] Collecting tests: sum.browser.test.js [Browser]
[INFO 1:48:04 PM] [Worker] Collecting /home/k/Projects/vitest-bugs/vitest-bug-4/sum.browser.test.js const __vite_ssr_import_0__ = await __vite_ssr_import__("/node_modules/vitest/dist/index.js", {"importedNames":["describe","it","expect"]});
const __vite_ssr_import_1__ = await __vite_ssr_import__("/sum.js", {"importedNames":["sum"]});



__vite_ssr_import_0__.describe("sum", () => {
    __vite_ssr_import_0__.it("sums numbers", () => {
        console.log("User Agent:", navigator.userAgent, "\n");
        __vite_ssr_import_0__.expect(__vite_ssr_import_1__.sum(1, 2)).toBe(3);
    });
});

//# sourceMappingSource=vite-node
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInN1bS5icm93c2VyLnRlc3QuanMiXSwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IHsgZGVzY3JpYmUsIGl0LCBleHBlY3QgfSBmcm9tIFwiL25vZGVfbW9kdWxlcy92aXRlc3QvZGlzdC9pbmRleC5qc1wiO1xuaW1wb3J0IHsgc3VtIH0gZnJvbSBcIi9zdW0uanNcIjtcblxuZGVzY3JpYmUoXCJzdW1cIiwgKCkgPT4ge1xuICAgIGl0KFwic3VtcyBudW1iZXJzXCIsICgpID0+IHtcbiAgICAgICAgY29uc29sZS5sb2coXCJVc2VyIEFnZW50OlwiLCBuYXZpZ2F0b3IudXNlckFnZW50LCBcIlxcblwiKTtcbiAgICAgICAgZXhwZWN0KHN1bSgxLCAyKSkudG9CZSgzKTtcbiAgICB9KTtcbn0pO1xuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLENBQUE7O0FBQTBFO0FBQzVDO0FBQzlCO0FBQ0EsOEJBQVEsQ0FBQyxDQUFDLEdBQUcsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQztBQUN2QixDQUFDLENBQUMsQ0FBQyxDQUFDLHdCQUFFLENBQUMsQ0FBQyxJQUFJLENBQUMsT0FBTyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO0FBQzlCLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxPQUFPLENBQUMsR0FBRyxDQUFDLENBQUMsSUFBSSxDQUFDLEtBQUssQ0FBQyxDQUFDLENBQUMsQ0FBQyxTQUFTLENBQUMsU0FBUyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUM7QUFDOUQsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLDRCQUFNLENBQUMseUJBQUcsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDLElBQUksQ0FBQyxDQUFDLENBQUMsQ0FBQztBQUNsQyxDQUFDLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxDQUFDO0FBQ1AsQ0FBQyxDQUFDLENBQUM7In0=

Skipping __vite_ssr_import__ (unknown call)
Skipping __vite_ssr_import__ (unknown call)
Skipping sum (unknown call)
Skipping expect (unknown call)
Found it sums numbers (run)
Found describe sum (run)
Found location for suite sum 6:0 -> 4:0
Found location for test sums numbers 7:4 -> 5:4
[1:48:05 PM] [VSCODE] Ignoring file: sum.browser.test.js.git
[1:48:05 PM] [VSCODE] Ignoring file: .git/FETCH_HEAD
[1:48:06 PM] [VSCODE] Ignoring file: sum.browser.test.js.git
[INFO 1:48:08 PM] [API] Collecting tests: sum.node.test.js [Node]
[1:48:08 PM] Not starting the runner because tests are being collected for sum.node.test.js
[1:48:08 PM] There is no test run for "sum.node.test.js [Node]"
[1:48:08 PM] No test run to finish for sum.node.test.js
[1:48:08 PM] [VSCODE] Ignoring file: node_modules/.vite/vitest/results.json
[1:48:10 PM] [VSCODE] File changed: sum.node.test.js
[INFO 1:48:10 PM] [Worker] Collecting tests due to file changes: sum.node.test.js
[1:48:10 PM] Not starting the runner because tests are being collected for sum.node.test.js
[Error 1:48:10 PM] Error in /home/k/Projects/vitest-bugs/vitest-bug-4/sum.node.test.js Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
    at TransformPluginContext._formatError (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49255:41)
    at TransformPluginContext.error (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49250:16)
    at TransformPluginContext.transform (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:63993:14)
    at async PluginContainer.transform (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49096:18)
    at async loadAndTransform (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51929:27)
    at async ViteNodeServer._transformRequest (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite-node/dist/server.mjs:537:16)
    at async ViteNodeServer._fetchModule (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite-node/dist/server.mjs:499:17)
    at async Proxy.fetch (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vitest/dist/chunks/resolveConfig.DPmbhVlP.js:6616:22)
    at async EventEmitter.onMessage (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vitest/dist/chunks/index.68735LiX.js:91:20)
[1:48:10 PM] There is no test run for "sum.node.test.js [Node]"
[1:48:10 PM] No test run to finish for sum.node.test.js
[1:48:10 PM] [VSCODE] Ignoring file: node_modules/.vite/vitest/results.json
[1:48:11 PM] [VSCODE] File changed: sum.node.test.js
[INFO 1:48:11 PM] [Worker] Collecting tests due to file changes: sum.node.test.js
[1:48:11 PM] Not starting the runner because tests are being collected for sum.node.test.js
[1:48:11 PM] There is no test run for "sum.node.test.js [Node]"
[1:48:11 PM] No test run to finish for sum.node.test.js
[1:48:12 PM] [VSCODE] Ignoring file: node_modules/.vite/vitest/results.json
[1:48:15 PM] [VSCODE] File changed: sum.browser.test.js
[INFO 1:48:15 PM] [Worker] Collecting tests due to file changes: sum.browser.test.js
Collecting using AST explorer...
[INFO 1:48:15 PM] [Worker] file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49255
    const err = typeof e === "string" ? new Error(e) : e;
                                        ^

Error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
    at TransformPluginContext._formatError (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49255:41)
    at TransformPluginContext.error (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49250:16)
    at TransformPluginContext.transform (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:63993:14)
    at async PluginContainer.transform (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:49096:18)
    at async loadAndTransform (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:51929:27)
    at async ViteNodeServer._transformRequest (file:///home/k/Projects/vitest-bugs/vitest-bug-4/node_modules/vite-node/dist/server.mjs:532:16)
    at async yo (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/worker.js:18:7457)
    at async Promise.all (index 0)
    at async e.astCollect (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/worker.js:20:1873)
    at async i.scheduleRerun (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/worker.js:8:31990) {
  plugin: 'vite:import-analysis',
  id: '/home/k/Projects/vitest-bugs/vitest-bug-4/sum.browser.test.js',
  pluginCode: 'import { describe, it, expect } from "vitest";\n' +
    'import { sum } from "./sum.js";\n' +
    '\n' +
    'describe("sum", () => {\n' +
    '    it("sums numbers", () => {\n' +
    '        console.log("User Agent:", navigator.userAgent, "\\n");\n' +
    '        expect(sum(1, 2)).toBe(3);\n' +
    '    });\n',
  loc: {
    file: '/home/k/Projects/vitest-bugs/vitest-bug-4/sum.browser.test.js',
    line: 1,
    column: 1
  },
  frame: '1  |  import { describe, it, expect } from "vitest";\n' +
    '   |  ^\n' +
    '2  |  import { sum } from "./sum.js";\n' +
    '3  |  '
}

Node.js v22.11.0
[1:48:15 PM] [API] Vitest child_process connection closed, cannot call RPC anymore.
[Error 1:48:15 PM] [API] Failed to close Vitest RPC [Error Error] [birpc] rpc is closed, cannot call "close"
Error: [birpc] rpc is closed, cannot call "close"
	at Proxy.$ (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:18:3709)
	at Lt.dispose (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:20:3126)
	at /home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:20:1707
	at Array.map (<anonymous>)
	at js.dispose (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:20:1698)
	at /home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:24:12326
	at ChildProcess.s (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:20:1465)
	at ChildProcess.emit (node:events:531:35)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[Error 1:48:20 PM] [API] Failed to close Vitest process [Error Error] Vitest process did not exit in time
Error: Vitest process did not exit in time
	at Timeout._onTimeout (/home/k/.vscode/extensions/vitest.explorer-1.6.4/dist/extension.js:20:3312)
	at listOnTimeout (node:internal/timers:581:17)
	at process.processTimers (node:internal/timers:519:7)
```

### Version

v1.6.4

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kayahr** [comment]
Fastest fix I've ever seen! Thanks!  :heart:
