### ISSUE TITLE
Plugin fails on startup with exit code 0

### ISSUE THREAD

**Issue by CarsonTolleshaug** [vitest-dev/vscode#524]
### Describe the bug

After installing the plugin, vscode reports that it cannot start the plugin because of an error. This same message is shown every time the project is loaded in vscode, and tests will not run. The error message shown looks like this:

![image](https://github.com/user-attachments/assets/a04e41ca-1609-42b4-86d4-a10222eb6897)

Clicking "See Error" shows the following output:
```
[INFO 4:43:45 PM] [v1.6.6] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 4:43:46 PM] [API] Running Vitest v2.1.2 (superusersearch-svelte/vite.config.ts) with Node.js@v20.14.0: C:\Program Files (x86)\Nodist\bin\node.EXE 
[Error 4:43:46 PM] [Error Error] Vitest process exited with code 0
Error: Vitest process exited with code 0
	at ChildProcess.E (c:\Users\[REDACTED]\.vscode\extensions\vitest.explorer-1.6.6\dist\extension.js:21:177)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

### Reproduction

The error seems to be hardware specific. I've never been able to run this extension, but my colleague was able to up until he upgraded to the same type of laptop as me (Dell Precision 5690). OS does not seem to be a factor either as he has Windows 11 on his new machine and I have Windows 10 and the same issue happens for both of us. Other colleagues with different hardware do not experience this issue.

It's worth noting that this model of laptop contains a dedicated GPU, where the others do not, so I'm wondering if this might be some sort of hardware acceleration issue.

I apologize for not being able to link to a repro due to the circumstances, I hope you understand.

To reiterate hardware specs:
- Windows 10 or 11
- Dell Precision 5690

Other potentially useful info:
- VS Code Version 1.95.1
- Vitest version 2.0.5
- Using Vitest in a SvelteKit project
- Using nodist to handle node version switching, currently set to version 20.14.0
- Other Vitest extensions do not have the same issue. Right now I'm using [Vitest Runner for VSCode that actually work](https://marketplace.visualstudio.com/items?itemName=rluvaton.vscode-vitest) though it does not provide a graphical UI

### Output

```shell
[INFO 4:43:45 PM] [v1.6.6] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 4:43:46 PM] [API] Running Vitest v2.1.2 (superusersearch-svelte/vite.config.ts) with Node.js@v20.14.0: C:\Program Files (x86)\Nodist\bin\node.EXE 
[Error 4:43:46 PM] [Error Error] Vitest process exited with code 0
Error: Vitest process exited with code 0
	at ChildProcess.E (c:\Users\[REDACTED]\.vscode\extensions\vitest.explorer-1.6.6\dist\extension.js:21:177)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess._handle.onexit (node:internal/child_process:294:12)
```

### Version

1.6.6

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by JustinSometimesWrong** [comment]
Yep same error I see:

```
[INFO 7:12:27 AM] [v1.6.6] Vitest extension is activated because Vitest is installed or there is a Vite/Vitest config file in the workspace.
[INFO 7:12:28 AM] [API] Running Vitest v2.1.2 ([REDACTED]/vite.config.ts) with Node.js@v20.10.0: C:\Program Files (x86)\Nodist\bin\node.EXE 
[Error 7:12:31 AM] [Error Error] Vitest process exited with code 0
Error: Vitest process exited with code 0
    at ChildProcess.E (c:\Users\[REDACTED]\.vscode\extensions\vitest.explorer-1.6.6\dist\extension.js:21:177)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess.emit (node:domain:488:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:294:12)

```

**Comment by tats-u** [comment]
You can't use this plugin *in Windows* due to this error.
Doesn't this error occur in other OSes?

**Comment by tats-u** [comment]
https://github.com/vitest-dev/vscode/blob/71f74dcdb874154381fb528da7414bb4c43bf3c7/src/api/child_process.ts#L97

**Comment by tats-u** [comment]
@MilanKovacic I'm using [proto](https://github.com/moonrepo/proto) as a version manager.

**Comment by tats-u** [comment]
It works for _me_.

**Comment by tats-u** [comment]
Is there any way except for the installation from VSIX in [the Marketplace](https://marketplace.visualstudio.com/items?itemName=vitest.explorer)?
I've enabled the auto update, but the new version hasn't come yet.

**Comment by sheremet-va** [comment]
> Is there any way except for the installation from VSIX in [the Marketplace](https://marketplace.visualstudio.com/items?itemName=vitest.explorer)? I've enabled the auto update, but the new version hasn't come yet.

You can click "install specific version"

![image](https://github.com/user-attachments/assets/672eb58e-5afb-4a1e-993a-4f962a704aac)

**Comment by tats-u** [comment]
I think 1.9.0 didn't appear at that time.

**Comment by sheremet-va** [comment]
> I think 1.9.0 didn't appear at that time. (I checked version list but no 1.9.0 there)

You need to enable pre-release versions to see it.

**Comment by tats-u** [comment]
I see. I switched to it and the version 1.9.0 was not changed. I misunderstood the "pre-release" label next to "Vitest" were to be a version.

**Comment by sheremet-va** [comment]
This should be fixed in 1.10.0 automatically.

**Comment by tats-u** [comment]
Oh, it's now stabilized. we don't have to stick to pre-release versions now.

@CarsonTolleshaug @JustinSometimesWrong You may want to report if this issue still occurs even in the latest version (1.10.0).

**Comment by CarsonTolleshaug** [comment]
Just confirmed it's working now. Thanks for the update!

**Comment by JustinSometimesWrong** [comment]
It's working in the latest release for me as well.  Thank you!

**Comment by tats-u** [comment]
I'm glad to hear those.
