### ISSUE TITLE
getCoreWorkspaceProject is not a function

### ISSUE THREAD

**Issue by wahmedswl** [vitest-dev/vscode#549]
### Describe the bug

```
[Error 6:59:41 PM] [API] Failed to refresh Vitest [Error Error] Vitest failed to start: 
TypeError: i.getCoreWorkspaceProject is not a function
    at new cr (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:8:31214)
    at new e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:1111)
    at process.e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:9196)
Error: Vitest failed to start: 
TypeError: i.getCoreWorkspaceProject is not a function
    at new cr (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:8:31214)
    at new e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:1111)
    at process.e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:9196)
	at ChildProcess.p (c:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\extension.js:20:3584)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess.emit (node:domain:488:12)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Reproduction

This is an existing project where Vitest was working; I have upgrade packages to the latest. This seems like conflict with the vitest extension and package version.

### Output

```shell
[Error 6:59:41 PM] [API] Failed to refresh Vitest [Error Error] Vitest failed to start: 
TypeError: i.getCoreWorkspaceProject is not a function
    at new cr (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:8:31214)
    at new e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:1111)
    at process.e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:9196)
Error: Vitest failed to start: 
TypeError: i.getCoreWorkspaceProject is not a function
    at new cr (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:8:31214)
    at new e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:1111)
    at process.e (C:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\worker.js:21:9196)
	at ChildProcess.p (c:\Users\HShakoor\.vscode\extensions\vitest.explorer-1.8.1\dist\extension.js:20:3584)
	at ChildProcess.emit (node:events:519:28)
	at ChildProcess.emit (node:domain:488:12)
	at emit (node:internal/child_process:951:14)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```
```


### Extension Version

v1.8.1

### Vitest Version

2.2.0-beta.2

### Validations

- [X] Check that you are using the latest version of the extension
- [X] Check that there isn't [already an issue](https://github.com/vitest-dev/vscode/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitest-dev/vscode/discussions) or join our [Discord Chat Server](https://chat.vitest.dev).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by AntonOfTheWoods** [comment]
I get the same error with `v3.0.0-beta.1`, but only in `vscode`, when running from `pnpm` it runs fine.

**Comment by wahmedswl** [comment]
Yes, the issue is with vscode only. CLI is working fine; it runs in watch mode so kinda like that as well.

**Comment by wahmedswl** [comment]
@sheremet-va Thanks! It's fixed 👍
